services:
  mariadb:
    build:
      context: ./requirements/MariaDB
    env_file: .env
    restart: always
  
  nginx:
    build:
      context: ./requirements/Nginx
    env_file: .env
    restart: always