services:
  mariadb:
    build:
      context: ./requirements/MariaDB
    env_file: .env
    restart: always
    volumes:
      - mariadb_data:  /home/shuppert/data

  wordpress:
    build: 
      context: ./requirements/WordPress
    env_file: .env
    restart: always
    volumes:
      - wordpress:  /home/shuppert/data
  
  nginx:
    build:
      context: ./requirements/Nginx
    env_file: .env
    restart: always