networks:
  my-network:
    driver: bridge

volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: none
      device: /home/svolodin/data/wp
      o: bind
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      device: /home/svolodin/data/db
      o: bind

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    env_file: .env
    ports:
      - "443:443"
      - "80:80"
    networks:
      - my-network
    volumes:
      - wp:/var/www/html
    depends_on:
      - wordpress
    restart: always
    
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/WordPress
    env_file: .env
    networks:
      - my-network
    volumes:
      - wp:/var/www/html
    depends_on:
      - mariadb
    expose:
      - "9000"
    restart: always


  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/MariaDB  
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - my-network
    expose:
        - "3306"
    restart: always

  adminer:
    container_name: adminer
    build: 
      context: ./requirements/bonus/Adminer
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - mariadb
    restart: on-failure

  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor
    image: cadvisor
    ports:
       - "8000:8080"
    networks:
     - my-network
    volumes:
      - /:/rootfs
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker/:/var/lib/docker
    restart: always
