CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'shuppert'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON wordpress.* TO 'shuppert'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root_1234';